# - Try to find the QIMAGE_BLITZ package -
# If found the following will be defined
#
#  QIMAGE_BLITZ_FOUND - QIMAGE_BLITZ package found on the system
#  QIMAGE_BLITZ_INCLUDE_DIR - Directory of the QIMAGE_BLITZ package include files
#  QIMAGE_BLITZ_LIBRARY - Where libkbfxcommon.so resides
#

FIND_PATH(QIMAGE_BLITZ_INCLUDE_DIR qimageblitz/qimageblitz.h
  PATHS
  ${INCLUDE_SEARCH_PATHES}
)

FIND_LIBRARY(QIMAGE_BLITZ_LIBRARY NAMES qimageblitz
  PATHS
  ${LIB_SEARCH_PATHES}
)

IF(QIMAGE_BLITZ_INCLUDE_DIR AND QIMAGE_BLITZ_LIBRARY)
   SET(QIMAGE_BLITZ_FOUND TRUE)
ENDIF(QIMAGE_BLITZ_INCLUDE_DIR AND QIMAGE_BLITZ_LIBRARY)

IF(QIMAGE_BLITZ_FOUND)
  IF(NOT QIMAGE_BLITZ_FIND_QUIETLY)
    MESSAGE(STATUS "Found QIMAGE_BLITZ package: ${QIMAGE_BLITZ_LIBRARY}")
  ENDIF(NOT QIMAGE_BLITZ_FIND_QUIETLY)
ELSE(QIMAGE_BLITZ_FOUND)
  IF(QIMAGE_BLITZ_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find QIMAGE_BLITZ package! Please download and install QIMAGE_BLITZ from http://websvn.kde.org")
  ENDIF(QIMAGE_BLITZ_FIND_REQUIRED)
ENDIF(QIMAGE_BLITZ_FOUND)

