
#define PLEXYNAME  "${APPLICATION_NAME}"
#define PLEXYVERSION  "${APPLICATION_MAIN_VERSION}"
#define PLEXYDATE  "${APPLICATION_DATE}"
#define PLEXYPREFIX  "${CMAKE_INSTALL_PREFIX}"
#define OPENCV_ROOT "${OpenCV_ROOT_DIR}"
#define BUILD_MODE "${CMAKE_BUILD_TYPE}"
#define PLEXYLIBDIR "${CMAKE_INSTALL_LIBDIR}"
