
#define BUILD_MODE "${CMAKE_BUILD_TYPE}"

#define PLEXYNAME  "${APPLICATION_NAME}"
#define PLEXYVERSION  "${APPLICATION_MAIN_VERSION}"
#define PLEXYDATE  "${APPLICATION_DATE}"

#define PLEXYPREFIX  "${CMAKE_INSTALL_PREFIX}"
#define PLEXYLIBDIR "${CMAKE_INSTALL_LIBDIR}"
#define PLEXYQTIMPORTSDIR "${QT_IMPORTS_INSTALL_DIR}"

#define OPENCV_ROOT "${OpenCV_ROOT_DIR}"
