######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 28 16:00:29 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += irc.h test.h
SOURCES += irc.cpp test.cpp
